runtime:
  heartbeat_interval: 10  # seconds
  log_level: INFO
  autosave_interval: 60  # seconds

llm:
  provider: openai  # or huggingface
  api_key: "YOUR_API_KEY_HERE"
  model: "gpt-3.5-turbo"
  endpoint: ""

storage:
  type: vector_db
  dim: 384

plugins:
  enabled:
    - tokenizer
    - normalizer
    - vectorizer
  tokenizer:
    type: default
    config: {}
  normalizer:
    type: default
    config: {}
  vectorizer:
    model: all-MiniLM-L6-v2

api:
  host: 0.0.0.0
  port: 8000
  auth_token: "changeme"