version: '3.8'
services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - API_KEY=your-secret-key
      - OPENAI_API_KEY=sk-test
      - DB_URL=sqlite:///kg.db
    volumes:
      - .:/app