site_name: ReasoningAgent Docs
nav:
  - Home: index.md
  - Architecture: architecture.md
  - Plugins: plugins.md
  - API Reference: api.md
  - Development: development.md
  - Contributing: contributing.md
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - search.suggest
    - search.highlight
    - toc.integrate
markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.tasklist
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets