workflow_id: data_preparation_workflow
steps:
  - id: ingest
    agent: data_ingestion1
    params:
      source: "sample.csv"
  - id: clean
    agent: data_cleaning1
    depends_on: [ingest]
  - id: transform
    agent: data_transformation1
    depends_on: [clean]
  - id: label
    agent: data_labeling1
    depends_on: [transform]
  - id: split
    agent: data_split1
    depends_on: [label]
  - id: export
    agent: data_export1
    depends_on: [split]
dag: true