apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  labels:
    app: agentsys

data:
  DATABASE_URL: postgresql://postgres:postgres@postgres:5432/agentsys
---
apiVersion: v1
kind: Secret
metadata:
  name: api-secrets
  labels:
    app: agentsys
stringData:
  API_KEY: changeme