apiVersion: apps/v1
kind: Deployment
metadata:
  name: neo4j
spec:
  replicas: 1
  selector:
    matchLabels:
      app: neo4j
  template:
    metadata:
      labels:
        app: neo4j
    spec:
      containers:
      - name: neo4j
        image: neo4j:5.19
        env:
        - name: NEO4J_AUTH
          value: neo4j/test
        ports:
        - containerPort: 7687
        - containerPort: 7474
---
apiVersion: v1
kind: Service
metadata:
  name: neo4j
spec:
  selector:
    app: neo4j
  ports:
    - port: 7687
      targetPort: 7687
    - port: 7474
      targetPort: 7474