apiVersion: v1
kind: Service
metadata:
  name: orchestrator
spec:
  type: LoadBalancer
  selector:
    app: orchestrator
  ports:
    - name: api
      port: 8000
      targetPort: 8000
    - name: metrics1
      port: 8001
      targetPort: 8001
    - name: metrics2
      port: 8002
      targetPort: 8002