apiVersion: v1
kind: Service
metadata:
  name: api-nodeport
spec:
  type: NodePort
  ports:
    - port: 8000
      nodePort: 30080
  selector:
    app: api
---
apiVersion: v1
kind: Service
metadata:
  name: dashboard-nodeport
spec:
  type: NodePort
  ports:
    - port: 8501
      nodePort: 30851
  selector:
    app: dashboard