version: '3.8'
services:
  orchestrator:
    build: .
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8002:8002"
    environment:
      - REDIS_URL=redis://redis:6379/0
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=test
    depends_on:
      - redis
      - elasticsearch
      - neo4j
      - prometheus
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
  neo4j:
    image: neo4j:5.19
    environment:
      - NEO4J_AUTH=neo4j/test
    ports:
      - "7687:7687"
      - "7474:7474"
  prometheus:
    image: prom/prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"