cursor/reasoning-agent-for-knowledge-graph-and-llm-interaction-bfb6

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:6-alpine
        ports:
          - 6379:6379
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install black isort flake8 mypy pytest pytest-cov
      - name: Lint (flake8)
        run: flake8 .
      - name: Format (black)
        run: black --check .
      - name: Import sort (isort)
        run: isort --check-only .
      - name: Type check (mypy)
        run: mypy .
      - name: Run tests
        run: pytest --cov=agent --cov=api --cov-report=xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: ./coverage.xml
          fail_ci_if_error: false
=======
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r multi_agent_framework/requirements.txt
    - name: Lint
      run: |
        pip install flake8
        flake8 multi_agent_framework/ tests/
    - name: Test
      run: |
        python -m unittest discover tests
    - name: Build Docker image
      run: |
        docker build -t orchestrator:ci multi_agent_framework/
> main