name: Deploy Docs

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          pip install mkdocs mkdocs-material pymdown-extensions mkdocstrings[python]
      - name: Build and Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      - name: Build docs
        run: mkdocs build